<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Lanos - Built on Slim3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:100,300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: 'Lato', sans-serif;
                text-align: center;
                color: #fff;
                font-size: 18px;
                background-color:#719e40;
            }

            h1 {
                color: #fff;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 100;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Lanos</h1>
        <div>A REST API Microframework for PHP</div>
            <p>Built on <a href="http://www.slimframework.com">SlimFramework</a></p>
    </body>
</html>
